POST http://localhost:3000/register/
Content-Type: application/json

{
    "name": "raja",
    "username": "ajay1234567",
    "password": "raja1234"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username": "raja1234",
    "password": "raja1234"
}